#!/bin/bash

# Configuration de PyVista pour l'environnement Binder
export PYVISTA_JUPYTER_BACKEND=panel
echo "export PYVISTA_JUPYTER_BACKEND=panel" >> ~/.bashrc

# Installation des extensions Jupyter nécessaires
jupyter nbextension enable --py widgetsnbextension
