#!/bin/bash

# Créez l'environnement à partir de environment.yml
conda env create -f environment.yml

# Activez l'environnement
source activate myenv  # Utilisez le nom de l'environnement que vous avez spécifié

# Activez les extensions Jupyter si nécessaire
jupyter nbextension enable --py --sys-prefix ipyvtklink
