name: fenics-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - fenics-dolfinx>=0.9.0
  - pyvista>=0.43.0
  - jupyter-book
  - meshio
  - h5py
  - seaborn
  - pandas
  - tqdm
  - pip
  - notebook
  - jupyter_contrib_nbextensions
  - ipywidgets
  - pip:
    - jupyter-offlinenotebook
