#!/bin/bash

# Créez l'environnement à partir de environment.yml
conda env create -f environment.yml

# Activez l'environnement
# L'activation d'un environnement conda dans un script peut nécessiter une méthode différente
# Dans un script non interactif, vous pouvez utiliser conda run

# Activez les extensions Jupyter
conda run -n my_pyvista_env jupyter nbextension enable --py --sys-prefix ipyvtklink
conda run -n my_pyvista_env jupyter nbextension enable --py widgetsnbextension
