#!/bin/bash

# Configuration de PyVista pour l'environnement Binder
export PYVISTA_JUPYTER_BACKEND=panel
echo "export PYVISTA_JUPYTER_BACKEND=panel" >> ~/.bashrc

# Installation et activation des extensions Jupyter
jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension

# Configuration pour PyVista
jupyter labextension install @pyviz/jupyterlab_pyviz
